//go:build !local_pdf_ocr
// +build !local_pdf_ocr

package chunk

import (
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"mime/multipart"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/itaiguardiola/askara/mlworker"
)

// extractEPUBTextLocal is not available without local_pdf_ocr build tag
// EPUB files should be processed by ML Worker or converted to another format
func extractEPUBTextLocal(content []byte) (string, error) {
	return "", fmt.Errorf("local EPUB processing not available: rebuild with '-tags local_pdf_ocr' or use ML Worker")
}

// extractTextWithOCRLocal uses ML Worker OCR with pdftoppm (lightweight approach)
func extractTextWithOCRLocal(f multipart.File) (string, error) {
	log.Println("[extractTextWithOCRLocal] Using ML Worker OCR with pdftoppm")

	mlClient := mlworker.GetClient()
	if !mlClient.IsFeatureEnabled("ocr") {
		return "", fmt.Errorf("ML Worker OCR feature not enabled")
	}

	// Reset file position
	_, err := f.Seek(0, io.SeekStart)
	if err != nil {
		return "", fmt.Errorf("seek error: %v", err)
	}

	// Read file content
	content, err := ioutil.ReadAll(f)
	if err != nil {
		return "", fmt.Errorf("read error: %v", err)
	}

	// Create temp directory
	tempDir, err := ioutil.TempDir("", "pdf-ocr-*")
	if err != nil {
		return "", fmt.Errorf("temp dir error: %v", err)
	}
	defer os.RemoveAll(tempDir)

	// Save PDF to temp file
	pdfPath := filepath.Join(tempDir, "input.pdf")
	err = ioutil.WriteFile(pdfPath, content, 0644)
	if err != nil {
		return "", fmt.Errorf("write PDF error: %v", err)
	}

	// Use pdftoppm to convert PDF pages to PNG images
	// -png: output as PNG
	// -r 150: 150 DPI for good OCR quality
	imgPrefix := filepath.Join(tempDir, "page")
	cmd := exec.Command("pdftoppm", "-png", "-r", "150", pdfPath, imgPrefix)
	output, err := cmd.CombinedOutput()
	if err != nil {
		log.Printf("[extractTextWithOCRLocal] pdftoppm error: %v, output: %s", err, output)
		return "", fmt.Errorf("pdftoppm error: %v", err)
	}

	// Find all generated PNG files
	files, err := filepath.Glob(filepath.Join(tempDir, "page-*.png"))
	if err != nil {
		return "", fmt.Errorf("glob error: %v", err)
	}

	if len(files) == 0 {
		return "", fmt.Errorf("no images generated by pdftoppm")
	}

	log.Printf("[extractTextWithOCRLocal] Processing %d pages with ML Worker OCR", len(files))

	var fullText strings.Builder

	// Process each page image with ML Worker OCR
	for i, imgPath := range files {
		// Read image and convert to base64 data URL
		imgData, err := ioutil.ReadFile(imgPath)
		if err != nil {
			log.Printf("[extractTextWithOCRLocal] Page %d: read error: %v", i+1, err)
			continue
		}

		// Check if image is too large for data URL
		b64Data := base64.StdEncoding.EncodeToString(imgData)
		dataURL := "data:image/png;base64," + b64Data

		if len(dataURL) > 100000 { // 100KB limit for safety
			log.Printf("[extractTextWithOCRLocal] Page %d: image too large (%d bytes), skipping", i+1, len(imgData))
			continue
		}

		// Call ML Worker OCR
		log.Printf("[extractTextWithOCRLocal] Page %d: Sending to ML Worker OCR (%d bytes)", i+1, len(imgData))
		ocrResp, err := mlClient.OCR(dataURL, "eng", true)
		if err != nil {
			log.Printf("[extractTextWithOCRLocal] Page %d: ML Worker OCR error: %v", i+1, err)
			continue
		}

		if ocrResp != nil && ocrResp.Text != "" {
			log.Printf("[extractTextWithOCRLocal] Page %d: OCR success (%.2f%% confidence, %d chars)",
				i+1, ocrResp.Confidence*100, len(ocrResp.Text))
			fullText.WriteString(ocrResp.Text)
			fullText.WriteString("\n\n")
		} else {
			log.Printf("[extractTextWithOCRLocal] Page %d: No text extracted", i+1)
		}
	}

	result := strings.TrimSpace(fullText.String())
	log.Printf("[extractTextWithOCRLocal] ML Worker OCR extracted %d characters total", len(result))

	if len(result) == 0 {
		return "", fmt.Errorf("no text extracted from any pages")
	}

	return result, nil
}
